import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
     <html>
      <body className='App flex flex-col min-h-screen'>
        <Navbar />
        <main className='flex-grow relative top-14'>
          {children}
        </main>
      </body>
    </html>
  )
}
